import { env } from '$env/dynamic/private';

const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta';

/**
 * Generate a 2x2 grid of product rotations using Gemini
 * @param {string} imageBase64 - The base64 encoded product image
 * @param {string} mimeType - The MIME type of the image
 * @returns {Promise<string>} - The base64 encoded canvas image (2x2 grid)
 */
export async function generateProductCanvas(imageBase64, mimeType = 'image/png') {
	if (!env.GOOGLE_GEMINI_API_KEY) {
		throw new Error('GOOGLE_GEMINI_API_KEY is not configured');
	}

	const prompt = `You will receive an uploaded product image. 

Generate four photorealistic images of the same product, maintaining perfect consistency in shape, proportions, colors, textures, reflections, and label design. Only change the rotation angle. Please pick rotation angle and rotation axis that's going to present our product provided the absolute best on an e-commerce product listing page. You must be sure the product is oriented correctly each image.

The final resulting image you generate will be on a 2x2 grid.

Angles to generate:
1. 90° rotation from original view
2. 180° rotation from original view
3. 270° rotation from original view
4. 360° / full-front return to original orientation (for consistency check)

Rules:
- Rotate only; do not alter design.
- Match lighting, shadows, and rendering style.
- Clean neutral studio background.
- Center the product in each frame.
- Photorealistic output.`;

	const response = await fetch(
		`${GEMINI_API_URL}/models/gemini-3-pro-image-preview:generateContent?key=${env.GOOGLE_GEMINI_API_KEY}`,
		{
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({
				contents: [{
					parts: [
						{ text: prompt },
						{
							inline_data: {
								mime_type: mimeType,
								data: imageBase64
							}
						}
					]
				}],
				generationConfig: {
					responseModalities: ['image', 'text']
				}
			})
		}
	);

	if (!response.ok) {
		const errorText = await response.text();
		throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
	}

	const data = await response.json();
	const imagePart = data.candidates?.[0]?.content?.parts?.find(
		(/** @type {any} */ part) => part.inlineData
	);

	if (!imagePart?.inlineData?.data) {
		throw new Error('No image generated by Gemini');
	}

	return imagePart.inlineData.data;
}

/**
 * @typedef {'top-left' | 'top-right' | 'bottom-left' | 'bottom-right'} QuadrantPosition
 */

/**
 * Extract a specific quadrant from a 2x2 grid image
 * @param {string} canvasBase64 - The base64 encoded canvas (2x2 grid)
 * @param {QuadrantPosition} position - The quadrant to extract
 * @returns {Promise<string>} - The base64 encoded extracted image
 */
export async function extractQuadrant(canvasBase64, position) {
	if (!env.GOOGLE_GEMINI_API_KEY) {
		throw new Error('GOOGLE_GEMINI_API_KEY is not configured');
	}

	/** @type {Record<QuadrantPosition, { rows: string; cols: string; corner: string }>} */
	const positionMap = {
		'top-left': { rows: '0-50%', cols: '0-50%', corner: 'UPPER-LEFT' },
		'top-right': { rows: '0-50%', cols: '50-100%', corner: 'UPPER-RIGHT' },
		'bottom-left': { rows: '50-100%', cols: '0-50%', corner: 'LOWER-LEFT' },
		'bottom-right': { rows: '50-100%', cols: '50-100%', corner: 'LOWER-RIGHT' }
	};

	const pos = positionMap[position];
	if (!pos) {
		throw new Error(`Invalid position: ${position}`);
	}

	const prompt = `CRITICAL TASK: CROP AND ZOOM INTO ONE QUADRANT ONLY.

The input image is a 2x2 collage containing 4 separate product photos arranged in a grid. You must ISOLATE and EXTRACT just ONE of these photos.

TARGET: ${pos.corner} QUADRANT
- This is the image in the ${pos.corner} corner (rows ${pos.rows} vertically, columns ${pos.cols} horizontally)
- It shows the product from a specific angle

WHAT TO DO:
1. IGNORE the other three photos completely
2. CROP to only the ${position.replace('-', ' ')} 25% of the total image area
3. ZOOM/UPSCALE this cropped section to fill your entire output canvas
4. The final output should look like a standalone product photo, not a collage

FORBIDDEN:
❌ Do NOT output all 4 images
❌ Do NOT output a grid or collage
❌ Do NOT show any dividing lines
❌ Do NOT include any part of the other 3 product photos

REQUIRED:
✅ Output exactly ONE product photo
✅ The product should fill the entire frame
✅ Clean background, single product only
✅ Match the quality and style of the original

Think of it like zooming in 200% on just the ${position.replace('-', ' ')} corner of the image.`;

	const response = await fetch(
		`${GEMINI_API_URL}/models/gemini-2.0-flash-exp-image-generation:generateContent?key=${env.GOOGLE_GEMINI_API_KEY}`,
		{
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({
				contents: [{
					parts: [
						{ text: prompt },
						{
							inline_data: {
								mime_type: 'image/png',
								data: canvasBase64
							}
						}
					]
				}],
				generationConfig: {
					responseModalities: ['image', 'text']
				}
			})
		}
	);

	if (!response.ok) {
		const errorText = await response.text();
		throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
	}

	const data = await response.json();
	const imagePart = data.candidates?.[0]?.content?.parts?.find(
		(/** @type {any} */ part) => part.inlineData
	);

	if (!imagePart?.inlineData?.data) {
		throw new Error(`No image extracted for position: ${position}`);
	}

	return imagePart.inlineData.data;
}
